version: "3"
services:
    web:
        container_name: web
        build: .
        ports:
            - "80:80"
        restart: always
        env_file:
            - .env
        volumes:
            - ./flask.sqlite:/myportfolio/flask.sqlite
        depends_on:
            - db
    db:
        container_name: db
        image: postgres
        restart: always
        env_file:
            - .env
    cadvisor:
        container_name: cadvisor
        image: gcr.io/cadvisor/cadvisor:latest
        restart: unless-stopped
        ports:
            - 8080:8080
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /var/lib/docker/:/var/lib/docker:ro
